FROM php:8.2-rc-apache-buster
RUN apt-get update && \
    apt full-upgrade -y && \
    apt autoremove -y
RUN docker-php-ext-install mysqli
RUN apt install nano -y
COPY ./index.php /var/www/html
COPY ./.bashrc /root/.bashrc
COPY ./.bash_aliases /root/.bash_aliases
EXPOSE 80
